server:
  port: 8082 #Asignamos el puerto del servidor
spring:
  application:
    name: tutorials-service #Nombre de la aplicación
  main:
    allow-bean-definition-overriding: true
#Al hacer esto, le estamos diciendo a Spring Boot que permita
  #la anulación de beans sin ningún cambio en las definiciones de
  #los beans.
  data:
    mongodb:
      host: 172.28.0.11 #definimos el host donde se alojará
  #mongodb.
      port: 27017 #definimos el puerto donde se alojará mongodb.